### ISSUE TITLE
Alan's Current To Do List

### ISSUE THREAD

**Issue by alanmitchell** [alanmitchell/bmon#49]
- [x] Eliminate Alaska Time Zone in code, issue #27
- [x] In the Install Article, describe the need to set up Email on the server for purposes of alerts.
- [x] In the Install Article, describe the optional need to set up a Pushover Application API Token.
- [x] Add Issue for coding alert routine.  Include processing notes from my small notebook.
- [x] Move Weather Underground key into settings file, issue #4 
- [x] Allow for multiple sensor reading storage keys, issue #50
